server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: processing-group
      payment-created-topic: payments.created
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  bank-adapter-url: http://localhost:8083

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 86400000 # a day
  refresh-expiration: 604800000 # 7 days
