server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**
  cache:
    cache-names:
      - buckets

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /api/v1/payments/**
      rate-limits:
        - bandwidths:
            - capacity: 100
              time: 1
              unit: minutes

jwt:
  secret: mysecretkeymysecretkeymysecretkeymysecretkey
  expiration: 86400000 # a day
  refresh-expiration: 604800000 # 7 days
